### ISSUE TITLE
self-referencing sprintf

### ISSUE THREAD

**Issue by eddiecwc** [LLNL/mdtest#1]
2724             strcat(testdir, TEST_DIR);
     2725             sprintf(testdir, "%s.%d", testdir, j);

in mdtest.c, sprintf of testdir references itself. When I tried to run this it wipes the original value of testdir completely and the new value of testdir is . followed by value of j.

**Comment by IanLee1521** [comment]
This repo is being archived, please see: https://github.com/MDTEST-LANL/mdtest instead.
