### ISSUE TITLE
Please kill/deprecate this repo

### ISSUE THREAD

**Issue by johnbent** [LLNL/mdtest#2]
Hello,

This repo appears to have been abandoned which is why LANL forked it to:
https://github.com/MDTEST-LANL/mdtest
However, that repo is also new deprecated because the mdtest code was moved into the IOR repo so that they share the abstract storage interface.  As such, please kill this repo to avoid community confusion or deprecate it and point people at the current version:
https://github.com/IOR-LANL/ior

**Comment by IanLee1521** [comment]
This repo is being archived using GitHub's archive functionality.
